spring:
  application:
    name: probation-offender-search

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: non_null
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${oauth.endpoint.url}/.well-known/jwks.json
      client:
        registration:
          community-api:
            provider: hmpps-auth
            client-id: ${oauth.client.id}
            client-secret: ${oauth.client.secret}
            authorization-grant-type: client_credentials
            scope: read
        provider:
          hmpps-auth:
            token-uri: ${oauth.endpoint.url}/oauth/token
server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto
      remote-ip-header: x-forwarded-for
  forward-headers-strategy: native

logging:
  level:
    org.springframework: INFO
    org.springframework.security: INFO
    uk.gov.justice.hmpps: DEBUG

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info, health'
  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-components: always
      show-details: always
      probes:
        enabled: true
    info:
      cache:
        time-to-live: 2000ms

azure:
  application-insights:
    web:
      enable-W3C: true

cloud:
  aws:
    stack:
      auto: false
    region:
      static: eu-west-2

search:
  supported:
    mapping:
      version: 1