version: 2.1

orbs:
  dps: ministryofjustice/dps@1.2.1
  owasp: entur/owasp@0.0.10

executors:
  builder:  
    docker:
      - image: circleci/openjdk:11-jdk-browsers
    working_directory: ~/app

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/openjdk:11-jdk-browsers
      - image: localstack/localstack:0.10.5
        environment:
          - SERVICES=es
          - ES_PORT_EXTERNAL=4571
          - DEBUG=${DEBUG- }
          - DATA_DIR=/tmp/localstack/data
          - DOCKER_HOST=unix:///var/run/docker.sock
          - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
          - AWS_EXECUTION_ENV=True
          - DEFAULT_REGION=eu-west-2
          - TMPDIR=/private
    steps:
      - checkout
      - run:
          name: Wait for localstack to start (will revisit)
          command: sleep 15
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
            - gradle-
      - run: ./gradlew build
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
      - persist_to_workspace:
          root: .
          paths:
            - build/libs
            - build.gradle

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - dps/helm_lint:
          name: helm_lint
      - dps/build_docker:
          name: build_docker
          filters:
            branches:
              only:
                - master
      - dps/deploy_env:
          name: deploy_dev
          env: "dev"
          filters:
            branches:
              only:
                - master
          requires:
            - helm_lint
            - build
            - build_docker
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - dps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          context: pathfinder-preprod
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - dps/deploy_env:
          name: deploy_prod
          env: "prod"
          slack_notification: true
          context: pathfinder-prod
          requires:
            - request-prod-approval

  scheduled:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5"
          filters:
            branches:
              only:
                - master
    jobs:
      - owasp/gradle_owasp_dependency_check:
          executor: builder

