apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.name" . }}
type: Opaque
data:
#  TODO: Fix app insights
#  APPINSIGHTS_INSTRUMENTATIONKEY: {{ .Values.secrets.APPINSIGHTS_INSTRUMENTATIONKEY | b64enc | quote }}
  APPINSIGHTS_INSTRUMENTATIONKEY: "Zm9vCg=="