# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/hmpps/offender-search
  tag: latest
  port: 8080

ingress:
  enabled: true
  enable_whitelist: false
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: offender-search-dev.prison.service.justice.gov.uk
      cert_secret: offender-search-cert
  path: /

env:
  JWT_PUBLIC_KEY: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF6Y3g3WWJ3MkJBV3Y3U3NFSVVHUAppeUpTSURndHFCeDE5VHdtN3VJM1RYNXpSY3JabFV4Y0VtUEpHVWd5K0QySkloVmxxbWVxd0dWMkNOT3FaQmdHCmo4ZUpHQTU5aUlUemU4ZG1SSk5JYzdsNmxESmc5RE5KVk9pTHFVbFpGRENJcXplSTYzb3E2dWhjY2c1RFBpVE4KcU9HWmM4dXBOK3c1ZFpyTnYrMkdMZ3hLMnBldE1VL0JoWWVXZjNLdllJTzE2djF1dm5GT0dPMTNIb1d1NUJ0ZApTdC9UZ2NsRmhWTEVkR3c3WGJpWUhuTlpJZGh3YU5RaVlnbVhtalpWZE15Q1BETW8xMExrVjFwM1V5MTVwTU14ClVwc2xKYU8wNlZIYXJtY3ZWYzNleHg5NlpHTjE2T2U4ZWZoeG5Rdmhzd0ZrbXlYT25sSForNDI1MnJHcHlKTG8KbHdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="
  JAVA_OPTS: "-Xmx512m"

kiam:
  roleArn: arn:aws:iam::754256621582:role/offender-search-elastic-search-delius-dev

elasticSearch:
  deliusRoleArn: arn:aws:iam::723123699647:role/cp-offender-search-service-role-delius-core-dev
  host: vpc-newtech-search-5vp7augmc5vncprjjbczf23g5q.eu-west-2.es.amazonaws.com
  port: 443
  scheme: https

nomisOAuth:
  JWT_JWK_SET_URI: https://gateway.t3.nomis-api.hmpps.dsd.io/auth/.well-known/jwks.json
