# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: quay.io/hmpps/offender-search
  tag: latest
  port: 8080

ingress:
  enabled: true
  enable_whitelist: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: offender-search-preprod.prison.service.justice.gov.uk
      cert_secret: offender-search-cert
  path: /

env:
  JWT_PUBLIC_KEY: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0NCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBalRkdXRLS2VQUkJlQWNrZ1M2cC8NCmxWK2Q1WXFiM3ExOHo2VXdoMU1OWXhwM0hxWXBZVis5MnlGeGUyUTVSN0tWakl5S3kyZkdBanNXeStlU04yM1QNCkZURVVUeXdHdnc0SkJrRGRoaUUvKy80SjR2TWFHMzBYN29GdE9JUWIwaENFQVlWM3o4emc1WVd2OGZlRkVnWGcNCkp3SjVCc2krU0NvajNIZDlERXk1ZGZaTTljL3BoOXN5YWpLU1ZiQW8rRCtXanhQWHU4UndRSk9BU0g0NUVwclQNCjNJMy9NdllyY1ZvdkN4UVZyUWNwYzNiY0U0bHpYdFlSVy9wSWpHUVpBKy9WYjNXZXZuR1FiYndTNHp6eXkzazgNCkRCZ0pzQVJlVDI1eHp0ckptRGlZZXBHYkVKVHV0alRqR2NVOG1qUjRWZ3gwdHdqMk9DMzBES3dXbGlrMzhXTWwNCk5RSURBUUFCDQotLS0tLUVORCBQVUJMSUMgS0VZLS0tLS0="
  JAVA_OPTS: "-Xmx512m"

whitelist:
  office: "217.33.148.210/32"
  health-kick: "35.177.252.195/32"
  mojvpn: "81.134.202.29/32"
  cloudplatform-live1-1: "35.178.209.113/32"
  cloudplatform-live1-2: "3.8.51.207/32"
  cloudplatform-live1-3: "35.177.252.54/32"

elasticSearch:
  deliusRoleArn: arn:aws:iam::010587221707:role/cp-offender-search-service-role-delius-pre-prod
  host: vpc-newtech-search-2zhrbjdmz4jbqx4i42f4brgoji.eu-west-2.es.amazonaws.com
  port: 443
  scheme: https

nomisOAuth:
  JWT_JWK_SET_URI: https://gateway.t3.nomis-api.hmpps.dsd.io/auth/.well-known/jwks.json