# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: quay.io/hmpps/probation-offender-search
  tag: latest
  port: 8080

ingress:
  enabled: true
  enable_allowlist: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: probation-offender-search.hmpps.service.justice.gov.uk
      cert_secret: probation-offender-search-cert
  path: /

env:
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "https://sign-in.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json"
  COMMUNITY_ENDPOINT_URL: "https://community-api-secure.probation.service.justice.gov.uk"
  JAVA_OPTS: "-Xmx512m"
  ES_PROXY_HOST: "aws-es-proxy-service"

allowlist:
  office: "217.33.148.210/32"
  health-kick: "35.177.252.195/32"
  mojvpn: "81.134.202.29/32"
  cloudplatform-live1-1: "35.178.209.113/32"
  cloudplatform-live1-2: "3.8.51.207/32"
  cloudplatform-live1-3: "35.177.252.54/32"
  delius-aws-1: "52.56.115.146/32"
  delius-aws-2: "35.178.104.253/32"
  delius-aws-3: "35.177.47.45/32"
  analyticplatform-1: "34.250.17.221/32"
  analyticplatform-2: "34.251.212.33/32"
  analyticplatform-3: "34.252.4.39/32"
